# wrangler.toml
name = "gemini-proxy-panel"
main = "worker/src/index.ts"
compatibility_date = "2025-03-27"
compatibility_flags = ["nodejs_compat"]

[assets]
binding = "ASSETS"
directory = "public"

[observability]
enabled = true

[triggers]
crons = ["*/30 * * * *"]

[[kv_namespaces]]
binding = "GEMINI_KEYS_KV"
id = "cacf1220ef4e47feb83d3259eff48cb4"

[[kv_namespaces]]
binding = "WORKER_CONFIG_KV"
id = "f4bc368de0de4fcd9db49f2d564f1ce3"
